drop view vi_sensor_t8;
drop view vi_sensor_t7;
drop view vi_sensor_t3;
drop view vi_sensor_t5;
drop view vi_sensor_k1;
drop view vi_sensor_t6;
drop view vi_sensor_T9;
drop procedure add_one_param_number;
drop function f_get_one_param_number;
